{
 "title": "Chef Automate HA - Component Health",
 "tags": [
  "chef",
  "automate",
  "automateha"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Chef Automate Load Balancer Status",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Chef Automate Load Balancer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"chef-automate-url\"}"
    }
   ]
  },
  {
   "title": "Chef Server Load Balancer",
   "type": "stat",
   "gridPos": { "h": 4, "w": 11, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=\"chef-server-url\"}"
    }
   ]
  },
  { "title": "Chef Frontend Server Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Chef Automate Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_http_status_code{job=~\"automate-services-.*\"}) by (job)"
    }
   ]
  },
  {
   "title": "Chef Infra Nodes",
   "type": "stat",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(probe_http_status_code{job=~\"chef-server-services-.*\"}) by (job)"
    }
   ]
  },
  {
   "title": "Chef Automate Services Status by nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 }
  },
  {
   "title": "Chef Automate - Node 1",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=~\"automate-services-node-01\"}"
    }
   ]
  },
  {
   "title": "Chef Automate - Node 2",
   "type": "stat",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=~\"automate-services-node-02\"}"
    }
   ]
  },
  {
   "title": "Chef Infra Services Status by nodes",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 }
  },
  {
   "title": "Chef Infra - Node 1",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=~\"chef-server-services-node-01\"}"
    }
   ]
  },
  {
   "title": "Chef Infra - Node 2",
   "type": "stat",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "probe_http_status_code{job=~\"chef-server-services-node-02\"}"
    }
   ]
  }
 ]
}