#global:
#  resolve_timeout: 1m


# alertmanager.yml

route:
  # A default receiver
  receiver: slack

  routes:
    - match:
        severity: L1
      receiver: pagerduty
      group_by: ['...']
      #    - match:
      #   severity: L2
      # receiver: slack
      # group_by: ['...']
    - match:
        severity: L2
      receiver: prometheus-msteams
      group_by: ['...']

receivers:
  - name: 'prometheus-msteams'
    webhook_configs: # https://prometheus.io/docs/alerting/configuration/#webhook_config
    - send_resolved: true
      url: 'http://localhost:2000/alertmanager'
  - name: pagerduty
    pagerduty_configs:
    - service_key: ADD_YOUR_KEY
      send_resolved: true
  - name: slack
    slack_configs:
      - api_url: 'ADD YOUR WEBHOOK URL'
        send_resolved: true
        channel: '#prometheus-monitoring'
        title: |-
          [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
          {{- if gt (len .CommonLabels) (len .GroupLabels) -}}
            {{" "}}(
            {{- with .CommonLabels.Remove .GroupLabels.Names }}
              {{- range $index, $label := .SortedPairs -}}
                {{ if $index }}, {{ end }}
                {{- $label.Name }}="{{ $label.Value -}}"
              {{- end }}
            {{- end -}}
            )
          {{- end }}
        text: >-
          {{ range .Alerts -}}
          *Alert:* {{ .Annotations.title }}{{ if .Labels.severity }} - `{{ .Labels.severity }}`{{ end }}

          *Description:* {{ .Annotations.description }}

          *Details:*
             {{ range .Labels.SortedPairs }} • *{{ .Name }}:* `{{ .Value }}`
             {{ end }}
          {{ end }}