groups:
 - name: chef services Health
   rules:
   - alert: ChefServicesHealth
     expr: probe_http_status_code{job=~"chef-server-services.*|automate-services.*"} != 200
     for: 10m
     labels:
       severity: page
     annotations:
       title: '{{ $labels.instance }} Down'
       description: '{{ $labels.instance }} site of job {{ $labels.job }} has been returning HTTP Code {{ $value }} for more than 10 minutes.'